name: test app

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

    jobs:
      unit-test:
        name: Run Tests
        run-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          uses: actions/setup-@nodev3
          with:
            node-version: "20"
        - run: npm install
        - run: npm run test